artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  copy_data: src/LiverTumorSegmentation/data/artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1pTnlnRERzBHNOT2P2gO9Mrql0nDm1H0W/view?usp=sharing
  local_data_file: artifacts/data_ingestion/Medical-Segmentation.zip
  unzip_dir: artifacts/data_ingestion

  